### PR TITLE
[Jenkins] Add new flag and logic to collect jobs

### LINKED ISSUE #617: How can I collect Jenkins Jobs recursively?
Hi, I'd like to collect build info from Jenkins.
I manage several jobs in separate folders.

like
http://localhost:8080/job/Group1/job/job-abc/
http://localhost:8080/job/Group1/job/job-def/
http://localhost:8080/job/Group2/job/job-xyz/

In this case, I can't get jobs with following configuration
```
jenkins:
  baseUrl: http://localhost:8080
```

As a workaround solution, I use different baseUrl per Jenkins Folder http://localhost:8080job/Group1/, http://localhost:8080job/Group2/
Is there any good solution?

### PR DESCRIPTION
**Pull request by TakiTake**
Resolve #617 

This is a feature addition proposal.
In order to reduce API calls, collect job name list with executing groovy script remotely.
Tentatively, I hardcode the groovy script so if you have any guideline to manage script resource, please let me know.

Thank you,
Takky

### CODE REVIEW

**Comment by Kesin11** [comment]
Thank you for creating pull-request.
I prefer to achieve this with a REST API, even if it requires a large number of API calls. But it is very interesting and I never thought of this way.

Can you give me a few more days? I'll try this new config on my Jenkins and if it has not any problem, I'll merge it.

**Review by Kesin11 — COMMENTED** [review]
If you write documentation as well, it would be great if you could add the new config to the sample yaml.
https://github.com/Kesin11/CIAnalyzer/blob/master/ci_analyzer.yaml#L59-L60

**Comment by TakiTake** [comment]
Thank you for your comment. Added the config sample.

**Review by Kesin11 — APPROVED** [review]
It works fine even on my Jenkins 👍 
Thank you!

**Pull request merged**
